# Generated by Django 2.0.7 on 2018-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_job',
            field=models.IntegerField(blank=True, default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
