# Generated by Django 2.0.7 on 2018-09-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0002_profile_count_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_url', 'Может видеть пункты меню'),)},
        ),
    ]
